blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/lrrsh/typescript-project-template#readme
    about: Please read the documentation before opening an issue
  - name: Discussions
    url: https://github.com/lrrsh/typescript-project-template/discussions
    about: Ask questions and discuss with the community
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/typescript
    about: Ask TypeScript related questions on Stack Overflow
